media:
  input: public
  output: ../..
content:
  - name: stickers
    label: Community Stickers
    path: public/content/stickers
    filename: '{fields.blog_slug}.json'
    type: collection
    fields:
      - name: title
        label: Title
        description: Title/header of the map popup that appears in black
        type: string
      - name: subtitle
        label: Subtitle
        description: Subtitle/caption of the map popup that appears in red
        type: string
      - name: icon
        label: Map Icon
        type: image
        multiple: false
      - name: long
        label: Longitude
        description: X-coordinate on the map
        type: number
        # TODO: min/max for boundaries or IL/Chicago
      - name: lat
        label: Latitude
        description: Y-coordinate on the map
        type: number
        # TODO: min/max for boundaries or IL/Chicago
      - name: blog_slug
        label: Featured Blog Post
        type: reference
        options:
          collection: posts
          # Shown before choosing the selection
          label: '{title} - {date}'
          # Shown after choosing the selection
          value: '{title} - {date}'
  - name: posts
    label: Posts
    type: collection
    path: 'public/content/posts'
    filename: '{fields.slug}.md'
    view:
      fields: [ title, published, date, imageList ]
    fields:
      - name: imageList
        label: Images
        type: image
        multiple: true
        required: false
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: slug
        label: Slug
        type: string
