export const INITIAL_STATE = {
  storedGeojson: {},
  currentData: 'tree_sst_master_tracts.geojson',
  columnNames: ["acs_population", "cities_casthma_prev", "cities_copd_prev", "svi_pecentile", "trees_n", "trees_area", "trees_den", "trees_crown_den", "asthma_5yr_avg", "asthma_age_adj_rate", "urban_flood_suscep", "heatisl", "nn_q3_pm2_5", "uchosp_casthma_visit", "logtraf", "hardship"],
  ranges:{},
  selectionData: {},
  filterValues: {},
  mapParams: {
    variableName:"Surface Temperature",
    numerator: 'properties',
    nType: 'charactertistic',
    nRange: null,
    nProperty: 'heatisl',
    denominator: 'properties',
    dType: null,
    dProperty: null,
    dRange:null,
    dIndex:null,
    scale:1,
    scale3D: 100,
    fixedScale: null,
    colorScale: [
      [255,255,178],
      [254,217,118],
      [254,178,76],
      [253,141,60],
      [240,59,32],
      [189,0,38],
    ],
    // defaults 
    zAxisParams: null,
    storedRange: null,
    bins: [],
    overlay: 'community_areas',
  },
  panelState: {
    variables:window.innerWidth > 768,
    info:window.innerWidth > 768,
    tutorial:false,
    context: false,
    contextPos: {x:null,y:null}
  },
  sidebarData: {},
  anchorEl: null,
  mapLoaded: false,
  notification: null,
  urlParams: {}
};